import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import Footer from './components/Footer'
import Header from './components/Header'

const roboto = Roboto({weight: ["500" , "100" , "300" , "400" , "700" , "900"], subsets: ["latin"]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
